version: '3.8'
services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: mysql:8
    #restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: mysqlpassword
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306